// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4QHnwGZKmvJ6yykljjsB6csOjE2qJPII',
    appId: '1:388909510648:android:7e9a189c382ce40383300d',
    messagingSenderId: '388909510648',
    projectId: 'parkme-19215',
    databaseURL: 'https://parkme-19215.firebaseio.com',
    storageBucket: 'parkme-19215.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABLuuLCQ1F6up-1ilA-PeYLNwk0kGPGyI',
    appId: '1:388909510648:web:845366df9e9fd95083300d',
    messagingSenderId: '388909510648',
    projectId: 'parkme-19215',
    authDomain: 'parkme-19215.firebaseapp.com',
    databaseURL: 'https://parkme-19215.firebaseio.com',
    storageBucket: 'parkme-19215.firebasestorage.app',
    measurementId: 'G-EX7NQT0W55',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEMfy3brlQCUe-2y6IKhrx06-KOo6PIS8',
    appId: '1:388909510648:ios:a0964938c6910a1f83300d',
    messagingSenderId: '388909510648',
    projectId: 'parkme-19215',
    databaseURL: 'https://parkme-19215.firebaseio.com',
    storageBucket: 'parkme-19215.firebasestorage.app',
    androidClientId: '388909510648-8ms51ld85uutdmp989kj0qqleks6otmn.apps.googleusercontent.com',
    iosClientId: '388909510648-k6i5ftbol2iag2r803fnplnl9psfd3gr.apps.googleusercontent.com',
    iosBundleId: 'com.mindhunter.parkme',
  );

}