// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzz45ZzuzVom-vBgM86CHT-RZz7EUM9is',
    appId: '1:880460554358:web:3b52e6b896b731f482ff57',
    messagingSenderId: '880460554358',
    projectId: 'culicars',
    authDomain: 'culicars.firebaseapp.com',
    storageBucket: 'culicars.firebasestorage.app',
    measurementId: 'G-4S5Q1FLFBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_igf5IXC4n1UWJkqmZWxYYJdGwW6rduY',
    appId: '1:880460554358:android:0d131b8a8499e18982ff57',
    messagingSenderId: '880460554358',
    projectId: 'culicars',
    storageBucket: 'culicars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0kM8pY0aNF9hpfo9irr-aVHG8YZGbaXs',
    appId: '1:880460554358:ios:b0d57671a5b07bc482ff57',
    messagingSenderId: '880460554358',
    projectId: 'culicars',
    storageBucket: 'culicars.firebasestorage.app',
    iosBundleId: 'com.mindberzerk.culicars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0kM8pY0aNF9hpfo9irr-aVHG8YZGbaXs',
    appId: '1:880460554358:ios:b89ddd40ded1a6cb82ff57',
    messagingSenderId: '880460554358',
    projectId: 'culicars',
    storageBucket: 'culicars.firebasestorage.app',
    iosBundleId: 'com.mindberzerk.culicars.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzz45ZzuzVom-vBgM86CHT-RZz7EUM9is',
    appId: '1:880460554358:web:b0a3a035e6e09e5182ff57',
    messagingSenderId: '880460554358',
    projectId: 'culicars',
    authDomain: 'culicars.firebaseapp.com',
    storageBucket: 'culicars.firebasestorage.app',
    measurementId: 'G-WLC9NZYS5R',
  );
}
